#!/bin/bash
# Note: bash.functions have been already applied.

alias psg='ps -aef | grep'
alias gst='git status'
alias grem='git remote -v'

alias nano='nano -w'
alias rnano='sudo nano -w -I'
alias pnano='nano -w -T 4 -E'

alias x='chmod +x'
alias h='history'
alias cd..='cd ..'
alias cdr='cd $REPOS && pwd && ls'
alias cdv='cd $VENVS && pwd && ls'

